name: "zelanko.github.io"
description: "Ari Zelankok on github"
url: "https://zelanko.github.io"
baseurl: /
timezone: "United Stages/Atlanta"
local: "en_us"

incremental: true
repository: zelanko/zelanko.github.io

webrick:
  headers:
    Content-Language: "en_us"